version: '3'

services:
  linx_bank_app:
    build: .docker/app/dev
    container_name: linx_bank_app
    tty: true
    ports:
      - "8081:8081"
    volumes:
      - .:/var/www
    networks:
      - app-network
  linx_bank_db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: linx_bank_db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=linx_bank
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=kanb_xnil
    # volumes:
    #   - ./.docker/mysqldata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge